/**
 * Provider patterns for API key detection
 */

import type { ProviderPattern } from './types'

export const PROVIDER_PATTERNS: ProviderPattern[] = [
  {
    provider: 'anthropic',
    label: 'Anthropic',
    icon: '🟣',
    patterns: [
      /sk-ant-api03-[A-Za-z0-9_-]{80,}/g,
      /sk-ant-[A-Za-z0-9_-]{40,}/g,
    ],
    searchQueries: [
      'sk-ant-api03',
      'sk-ant-api',
      'ANTHROPIC_API_KEY sk-ant',
      'anthropic_key sk-ant',
      'sk-ant path:.env',
      'sk-ant path:.yml',
      'sk-ant language:Python',
      'sk-ant language:JavaScript',
      'sk-ant language:TypeScript',
      'claude api_key sk-ant',
      'sk-ant path:docker-compose',
      'sk-ant path:config.json',
      'sk-ant path:.env.production',
      'anthropic_api_key path:settings',
      'claude sk-ant path:mcp',
      'sk-ant path:secrets',
    ],
  },
  {
    provider: 'openai',
    label: 'OpenAI',
    icon: '🟢',
    patterns: [
      /sk-proj-[A-Za-z0-9_-]{40,}/g,
      /sk-[a-zA-Z0-9]{20,}/g,
    ],
    searchQueries: [
      'sk-proj-',
      'OPENAI_API_KEY sk-',
      'openai_api_key sk-',
      'openai.api_key sk-',
      'sk-proj- path:.env',
      'sk-proj- path:.yml',
      'OPENAI_API_KEY language:Python',
      'OPENAI_API_KEY language:JavaScript',
      'openai_key sk- language:Dotenv',
      'sk- path:.env.local',
      'sk-proj- path:docker-compose',
      'openai_api_key path:config.json',
      'sk- path:.env.production',
      'openai sk- path:appsettings',
      'OPENAI_API_KEY path:serverless',
    ],
  },
  {
    provider: 'google',
    label: 'Google AI',
    icon: '🔵',
    patterns: [
      /AIza[A-Za-z0-9_-]{35}/g,
    ],
    searchQueries: [
      'GEMINI_API_KEY AIza',
      'GOOGLE_API_KEY AIza',
      'google_api_key AIza',
      'AIzaSy path:.env',
      'AIzaSy path:.yml',
      'AIzaSy language:Python',
      'AIzaSy language:JavaScript',
      'generativelanguage AIzaSy',
      'gemini AIzaSy',
      'AIzaSy path:docker-compose',
      'AIzaSy path:config.json',
      'AIzaSy path:.env.production',
      'google_api_key AIzaSy path:secrets',
    ],
  },
  {
    provider: 'xai',
    label: 'xAI (Grok)',
    icon: '⚪',
    patterns: [
      /xai-[A-Za-z0-9]{20,}/g,
    ],
    searchQueries: [
      'XAI_API_KEY xai-',
      'xai_api_key xai-',
      'xai- grok api',
      'xai- path:.env',
      'xai- language:Python',
      'x.ai api_key xai-',
      'xai- path:docker-compose',
      'xai- path:config.json',
    ],
  },
  {
    provider: 'groq',
    label: 'Groq',
    icon: '🟠',
    patterns: [
      /gsk_[A-Za-z0-9]{20,}/g,
    ],
    searchQueries: [
      'GROQ_API_KEY gsk_',
      'groq_api_key gsk_',
      'gsk_ path:.env',
      'gsk_ language:Python',
      'gsk_ language:JavaScript',
      'groq api key gsk_',
      'gsk_ path:docker-compose',
      'gsk_ path:config.json',
    ],
  },
  {
    provider: 'cerebras',
    label: 'Cerebras',
    icon: '🔴',
    patterns: [
      /csk-[A-Za-z0-9]{20,}/g,
    ],
    searchQueries: [
      'CEREBRAS_API_KEY csk-',
      'cerebras_api_key csk-',
      'csk- path:.env',
      'csk- language:Python',
      'csk- path:docker-compose',
      'csk- path:config.json',
    ],
  },
  {
    provider: 'openrouter',
    label: 'OpenRouter',
    icon: '🟡',
    patterns: [
      /sk-or-v1-[A-Za-z0-9]{40,}/g,
    ],
    searchQueries: [
      'sk-or-v1-',
      'OPENROUTER_API_KEY sk-or-v1-',
      'openrouter_api_key sk-or-v1-',
      'sk-or-v1- path:.env',
      'sk-or-v1- language:Python',
      'openrouter sk-or-v1-',
      'sk-or-v1- path:docker-compose',
      'sk-or-v1- path:config.json',
    ],
  },
  {
    provider: 'mistral',
    label: 'Mistral AI',
    icon: '🔷',
    patterns: [
      /[A-Za-z0-9]{32}/g,
    ],
    searchQueries: [
      'MISTRAL_API_KEY',
      'mistral_api_key path:.env',
      'mistral_key language:Python',
      'mistral api_key path:config',
      'mistral path:.env.production',
    ],
  },
  {
    provider: 'cohere',
    label: 'Cohere',
    icon: '🟤',
    patterns: [
      /[A-Za-z0-9]{40}/g,
    ],
    searchQueries: [
      'COHERE_API_KEY co-',
      'cohere_api_key path:.env',
      'cohere api_key language:Python',
      'COHERE_API_KEY path:config',
      'cohere_key path:.env.production',
    ],
  },
  {
    provider: 'together',
    label: 'Together AI',
    icon: '🤝',
    patterns: [
      /[a-f0-9]{64}/g,
    ],
    searchQueries: [
      'TOGETHER_API_KEY',
      'together_api_key path:.env',
      'TOGETHER_API_KEY language:Python',
      'together ai api_key path:config',
      'togetherai path:.env',
    ],
  },
  {
    provider: 'replicate',
    label: 'Replicate',
    icon: '🔁',
    patterns: [
      /r8_[A-Za-z0-9]{36,}/g,
    ],
    searchQueries: [
      'REPLICATE_API_TOKEN r8_',
      'r8_ path:.env',
      'replicate_api_token r8_',
      'r8_ language:Python',
      'replicate r8_ path:config',
      'r8_ path:docker-compose',
    ],
  },
  {
    provider: 'huggingface',
    label: 'Hugging Face',
    icon: '🤗',
    patterns: [
      /hf_[A-Za-z0-9]{30,}/g,
    ],
    searchQueries: [
      'hf_ HF_TOKEN',
      'HUGGINGFACE_API_KEY hf_',
      'hf_ path:.env',
      'hf_ language:Python',
      'huggingface_token hf_',
      'HF_TOKEN hf_ path:config',
      'hf_ path:docker-compose',
    ],
  },
  {
    provider: 'deepseek',
    label: 'Deepseek',
    icon: '🐋',
    patterns: [
      /sk-[a-f0-9]{48,}/g,
    ],
    searchQueries: [
      'DEEPSEEK_API_KEY sk-',
      'deepseek_api_key path:.env',
      'deepseek api_key language:Python',
      'deepseek sk- path:config',
      'deepseek_key path:.env.production',
    ],
  },
  {
    provider: 'fireworks',
    label: 'Fireworks AI',
    icon: '🎆',
    patterns: [
      /fw_[A-Za-z0-9]{30,}/g,
    ],
    searchQueries: [
      'FIREWORKS_API_KEY fw_',
      'fireworks_api_key fw_',
      'fw_ path:.env',
      'fw_ language:Python',
      'fireworks fw_ path:config',
    ],
  },
]
